In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
upload = pd.read_csv('upload.csv')
train = train.dropna(axis = 1, how = 'all')
test = test.dropna(axis = 1, how = 'all')
# test.head()

In [3]:
temp = ['RowNumber', 'CustomerId', 'Surname', 'Exited']
train_X = train.drop(temp, axis = 1) 
train_y = train['Exited']
test_X = test.drop(temp[0:3], axis = 1)


In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
labelencoder = LabelEncoder()
train_X['Geography'] = labelencoder.fit_transform(train_X['Geography'])
train_X['Gender'] = labelencoder.fit_transform(train_X['Gender'])
train_X['Age'] = preprocessing.scale(train_X['Age'])
train_X['Tenure'] = preprocessing.scale(train_X['Tenure'])
train_X['Balance'] = preprocessing.scale(train_X['Balance'])
train_X['EstimatedSalary'] = preprocessing.scale(train_X['EstimatedSalary'])


In [5]:
test_X['Geography'] = labelencoder.fit_transform(test_X['Geography'])
test_X['Gender'] = labelencoder.fit_transform(test_X['Gender'])
test_X['Age'] = preprocessing.scale(test_X['Age'])
test_X['Tenure'] = preprocessing.scale(test_X['Tenure'])
test_X['Balance'] = preprocessing.scale(test_X['Balance'])
test_X['EstimatedSalary'] = preprocessing.scale(test_X['EstimatedSalary'])

In [21]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2,random_state=42)
labels = kmeans.fit_predict(test_X)
labels

array([0, 0, 1, ..., 1, 1, 1])

In [22]:
from sklearn.cluster import DBSCAN
clustering = DBSCAN(eps=3, min_samples=2).fit(test_X)
clustering.labels_

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [6]:
classifier = KNeighborsClassifier()
classifier.fit(train_X, train_y)
pred_y = classifier.predict(test_X)
pred_y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
from xgboost import XGBClassifier
xgboostModel = XGBClassifier(n_estimators=100, learning_rate= 0.3)
xgboostModel.fit(train_X,train_y)
# 使用訓練資料預測分類
predicted = xgboostModel.predict(test_X)
predicted

In [ ]:
classifer=LogisticRegression()
classifier.fit(train_X,train_y)
pred_yy=classifier.predict(test_X)
pred_yy

In [24]:
upload['Exited'] = clustering.labels_
upload.to_csv('4.csv')